Add basic multi-level list support to Text.rakumod
rakudo/rakudo pull request #4197
Opened 2021-02-08 18:47 UTC by hopkinsza

2021-02-11 20:54 UTC, vrurg commented
@hopkinsza Would it be possible for you to provide more information and take care of the failing tests?

2021-02-11 22:13 UTC, hopkinsza commented
Apologies for using you as my guinea pig as I learn the github process -- this patch improves the output of Pod::To::Text by adding indentation for pod6 items based on their level.

For example, given the following script:

```
use Pod::To::Text;

=begin pod
=item item
=item2 item2
=item3 item3
=item item
=item2 item2
=end pod

say pod2text($=pod);
```

The current output would be:

```
  * item

  * item2

  * item3

  * item

  * item2
```

After this modification, the output is:

```
  * item

    * item2

      * item3

  * item

    * item2
```

2021-02-12 06:26 UTC, JJ requested changes
Please mind the errors.

2021-02-12 06:26 UTC, JJ commented on lib/Pod/To/Text.rakumod
> +        when Pod::Item              { item2text($pod).               }
The `.` is a syntax error, that's what's making the errors pop up.

2021-02-13 04:48 UTC, hopkinsza commented
Must open a new pull request since I foolishly deleted and remade my fork while troubleshooting -- and GitHub will not let me edit this one to use that new repo 😅. Sorry again for this! However, the error should be fixed.

@vrurg
See #4202.

2021-02-13 04:48 UTC, closed without merging