Make raku installation portable
rakudo/rakudo pull request #4968
Opened 2022-06-25 08:41 UTC by locriacyber

- [X] Create portable installation with `zef install --prefix=yourrepohere .`
- [ ] Make raku/moarvm portable (use relative path to get dependencies)

2022-06-25 08:41 UTC, locriacyber commented on src/core.c/CompUnit/Repository/Installation.pm6
> +    my $vendor_dir = $*SPEC.catdir($?FILE.IO.dirname, '..').IO.resolve;
`.IO.resolve` is technically unnecessary.

2022-06-27 18:55 UTC, ugexe requested changes
This PR modifies the repo chain when it should not. fwiw I don't really understand what your issue is (installing to e.g. vendor works fine for me, and I'm not familiar with anyone else ever having such a problem), but this change would be a regression.

2022-06-28 03:01 UTC, locriacyber commented
What vendor? I need to make the application to be run anywhere.
AFAIK the current Repository use absolute path.

2022-06-28 06:07 UTC, niner commented
That is already supported. Rakudo can be built in a relocatable version with `perl Configure.pl --relocatable`. From the `--help` text:
```
    --relocatable      Dynamically locate NQP and Perl6 home dirs instead of
                       statically compiling them in. (On AIX and OpenBSD Rakudo
                       is always built non-relocatable, since both OSes miss a
                       necessary mechanism.)
```

2022-06-28 06:07 UTC, closed without merging

2022-07-05 12:58 UTC, abraxxa commented
Does this help text really still read 'Perl6'?