Fix for storing parameterised hashes as items
rakudo/rakudo pull request #5169
Opened 2023-01-26 00:56 UTC by 2colours

Belongs to https://github.com/rakudo/rakudo/issues/5165.

STORE_AT_KEY receives high level key-value arguments, they might not be available from the underlying $!storage directly. The classes/roles that implement STORE_AT_KEY (and hence know how their $!storage is composed), should also know and provide how to interpret a BOOTIter entry back to a high-level key-value pair. Another solution could be to expose and overload STORE_MAP directly for the subtypes.

2023-01-26 19:51 UTC, niner requested changes
The commit message does not explain what the problem is that this commit solves. Since I don't know what the problem is, I cannot tell if your solution is a good fix for it.

Also please follow commit message formatting conventions, i.e. wrap lines longer than 80 characters.

2023-01-26 21:42 UTC, 2colours commented
I think both the commit message and the linked issue explain the problem, on two different levels. If it's still not clear after reading both, maybe let's talk about it.

I'm going to reformat the commit message - alas, a vanilla nano editor doesn't give me much sense of aesthetics.

2023-01-27 07:11 UTC, niner commented
Please include all relevant information in the commit message. This code base and repository lives for decades. We don't know whether the link will still work in 20 years. Also finding out why something is the way it is, is already hard enough, without having to switch between git log in the terminal and the browser to get that additional information.

2023-01-27 07:37 UTC, jonathanstowe commented
> Please include all relevant information in the commit message.

Not entirely related to this ticket but I made exactly the same point to my colleagues yesterday morning: if the _why_ isn't in a commit message some future developer may not have any other way of knowing the purpose of a change.

2023-01-27 09:14 UTC, 2colours commented
Please be more specific about what you consider "relevant information" so that I don't have to guess. For me, saying that this method assumed a certain simple way of obtaining the key and the value - while this is something that all Hash implementations that have their own STORE, decide for themselves, seemed enough and will continue to seem enough, unless you can elaborate on what you miss.

2023-01-27 09:23 UTC, niner commented
I don't know what I miss because I don't understand what's there. What does "high level key-value arguments" mean exactly? What would low level be in comparison?

What is the user-visible problem that this solves? E.g. what Raku code gives which result before and after your change and why was the result before the change wrong and the result after the change correct?

Is the new PUT_FROM_ITER method on Hash::Object meant to be a public API? E.g. do we expect subclasses written by users to provide this method?

2023-01-27 09:57 UTC, 2colours commented
> What does "high level key-value arguments" mean exactly? What would low level be in comparison?

low-level keys and values are the ones stored in the underlying `$!storage` (which is a `BOOTHash` I think, and only knows string keys) - as opposed to fully-fledged Raku `Hash`es that the users access and deal with, the "high level" key and value.

If you can say how to point out this dichotomy in a clear way, I'll be welcome to change it to that. To be honest, I don't think it's my task as the author of a bugfix to explain the already existing essential architecture, and especially not in a commit message.

> Is the new PUT_FROM_ITER method on Hash::Object meant to be a public API? E.g. do we expect subclasses written by users to provide this method?

I mean, the answer is already there...

> The classes/roles that implement STORE_AT_KEY (and
hence know how their $!storage is composed), should
also know and provide how to interpret a BOOTIter
entry back to a high-level key-value pair.

To be honest, I think this should answer all questions of this sort, and exactly them. For what it's worth, STORE_AT_KEY is not something I added and it's not public API. However, should we have another Hash that needs to provide its own STORE_AT_KEY, it should also provide its own PUT_FROM_ITER - that's what the message says. I wanted to highlight the important bits but it says pretty much exactly this.

> What is the user-visible problem that this solves? E.g. what Raku code gives which result before and after your change and why was the result before the change wrong and the result after the change correct?

I have mixed feelings whether that belongs there but I'd definitely expect that you read the issue and could immediately see the Raku code? Also, I hadn't had time to immediately add Roast tests but now I made [a PR for that as well](https://github.com/Raku/roast/pull/828).

> I don't know what I miss because I don't understand what's there.

Well, sorry if this is mean I something - my impression is that you could have read at least the relevant context that is easily available from the issue and the referenced code I didn't write, you'd have quite surely understood the situation, AND then say exactly what you are missing, with that understanding. Instead, what I kinda see is that you are making an unnecessary point from an unrelatable hypothetical perspective. The questions you asked now are useful for communicating but when I see that it should have been answered already, it's hard to make any improvement.

2023-01-27 10:03 UTC, lizmat commented
Taken a different approach that would affect performance in most cases a lot less in https://github.com/rakudo/rakudo/commit/932df924f8

Closing this PR

2023-01-27 10:03 UTC, closed without merging